version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  simulator:
    build: ./simulator
    ports:
      - 3000:3000
    environment:
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
      - POLLING_INTERVAL=${POLLING_INTERVAL}
      - SERVER_PORT=${SERVER_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
    depends_on:
      - mosquitto
  backend:
    build: ./backend
    ports:
      - 8080
    environment:
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
      - WS_PORT=${WS_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
    depends_on:
      - mosquitto
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL}
    ports:
      - 80
  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
